### ISSUE TITLE
Uncloseable thread pools in Client class

### ISSUE THREAD

**Issue by aldan95** [centrifugal/centrifuge-java#13]
There are 3 internal executors with thread pools in Client class:
- executor
- reconnectExecutor
- scheduler
every executor keeps own thread pool with single **_non-daemon_** thread, which prevents java app from regular termination.
There are no method to stop these threads on exit and gracefully stop the application.
I suggest to add `shutdown()` method similar as `disconnect()` but with shutdown of internal executors.

**Comment by FZambia** [comment]
@aldan95 hello, thanks! Since Java is not my day to day language I could miss things like this.

I suppose your suggestion makes a lot of sense and we should add this. Could you send pull request?

**Comment by FZambia** [comment]
`Client.Close` method added in September 2020, just notices that I have not closed this issue.
