### ISSUE TITLE
Stuck on connecting state after getting bad request during the first connect.

### ISSUE THREAD

**Issue by agent10** [centrifugal/centrifuge-java#31]
Steps to reproduce:
1) (In my case) Get any malformed url, e.g.: wss://correcturl/ws?format=protobufABCDE. So this is almost correct url except the last part.
2) Create Client with the url, set all listeners and callbacks properly.
3) Call connect() method. See that only onDisconnected callback called with "bad request, reconnect = false"
4) Call connect() again. Nothing happened.
4.1) Call disconnect() / connect() in any order. The same result, no any callbacks called.

Debugging shows that in this case the second and others connect() methods don't make sense anymore because Client.connecting field is still true and will never change to false.

**Comment by FZambia** [comment]
Hello, thanks for detailed report.

In general, the case you described is an error which can't be solved by reconnect, that's an application error which should be solved on application development stage.

But for broader use cases I agree – connecting field should be set to `false` upon getting disconnect with `"reconnect": false`.

**Comment by FZambia** [comment]
SDK >= v0.2.0 does not have connecting field anymore and should properly connect from disconnected state.
