### ISSUE TITLE
options.setToken() seems not worked

### ISSUE THREAD

**Issue by meghdadfm** [centrifugal/centrifuge-java#37]
Hello again
on the web :
    the setToken() method works fine and generated token is worked. when we do not call setToken, received bad request Error on server side. when we call the method but send empty token, we received 'invalid token' error on server.
now on android:
   I think setToken() method not worked properly because we always get this error on server side : bad request . and on android I received this error:

System.out: [socket]:check permission begin!
System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
System.out: [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
CentriFugo: error = Client error  java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'

last line is my log on EventListener : override fun onError(client: Client?, event: ErrorEvent)

**Comment by FZambia** [comment]
Hello!

`Expected HTTP 101 response but was '403 Forbidden'` line signal about WebSocket connection problem, nothing related to token at this point. So make sure you are not getting 403 responses on WebSocket Upgrade requests.

Could you try running our [example](https://github.com/centrifugal/centrifuge-java/blob/master/example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java)? I am pretty sure it worked with token and latest Centrifugo as I checked this during development of the latest version.

**Comment by meghdadfm** [comment]
Thank you for response.
Let me know, what is WebSocket Upgrade requests ?

**Comment by FZambia** [comment]
This SDK uses WebSocket transport to connect to a server. WebSocket transport starts from HTTP Upgrade - see [rfc](https://datatracker.ietf.org/doc/html/rfc6455#section-1.3) and [this doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism) for example. After successful connection server returns HTTP code 101 to a client.

The fact that you are getting HTTP 403 instead of 101 makes me feel that there are some issues with WebSocket connection. Probably some proxy or sth.

Check out [readme](https://github.com/centrifugal/centrifuge-java#basic-usage), it also mentions:

```
<uses-permission android:name="android.permission.INTERNET" />
```

In AndroidManifest.xml.

Try running example I pointed in comment above. I just tried to run it with valid token (i.e. uncommented `setToken` call in example and replaced token with actual one) and Client successfully connected to Centrifugo v4.

**Comment by meghdadfm** [comment]
I am working on your demo example from the first, not my project. Thats right, it is about websocket not token. I added a logging intercepter to okhttp and see request and body values. There should be some other values that I can not see in that log. I am trying to make a better log of what sent to server

**Comment by meghdadfm** [comment]
Hello again
WebSocket upgrading is ok on websocket as I see token I sent on my server log. it shows handshaking is finished successfully. I have error in websocket method ' public void onFailure(WebSocket webSocket, Throwable t, Response response) '. 
We compare server logs for both web and android. there is a diffrence on a key : see "params" key in web log and instead "connect" in android log.

Web : 
{"level":"info","client":"127d883c-661a-4083-ab75-00adc3f813f6","command":"id:1  params:\"{\\\"token\\\":\\\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtleS1tZWdoZGFkdIn0.e30.jbsuni14QOMhJsPxwdglQAvhhReTe9oMlcgLrbzRscU\\\",\\\"name\\\":\\\"js\\\"}\"","reason":"invalid token","user":"","time":"2022-07-26T09:26:18Z","message":"disconnect after handling command"}

Android : 
{"level":"info","client":"f67b16e7-7ad5-46c4-9d1b-8419e79fd17f","command":"id:1  connect:{token:\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJpYXQiOjE2NTg3NDYzMTB9.LosCTc7TTmGxV2IuVdidA6AIXZK5XTeRXK6xGi1gYhQ\"  name:\"java\"}","reason":"bad request","user":"","time":"2022-07-25T10:54:48Z","message":"disconnect after handling command"}

**Comment by FZambia** [comment]
We released Centrifugo recently. Web uses client protocol v1, Java client >= 0.2.0 uses client protocol v2.

All information can be found in links:

1. [Release post](https://centrifugal.dev/blog/2022/07/19/centrifugo-v4-released)
2. [Migration guide](https://centrifugal.dev/docs/getting-started/migration_v4)
3. [Centrifugo v4 release notes](https://github.com/centrifugal/centrifugo/releases/tag/v4.0.0)
4. [centrifuge-java v0.2.2 release notes](https://github.com/centrifugal/centrifuge-java/releases/tag/0.2.2)

In your case if you want to work in a way similar to Web client you need to use centrifuge-java v0.1.0 (which has different API compared to v0.2.2).

**Comment by FZambia** [comment]
Closing, as I don't see nothing actionable here
