### ISSUE TITLE
How can I subscribe to private channel?

### ISSUE THREAD

**Issue by LuisOzParr** [centrifugal/centrifuge-java#4]
Hi. I read that in Javascript client AJAX POST request is automatically sent to ```/centrifuge/subscribe``` endpoint on every private channel subscription attempt.
But In Java (Android) what is the manner to connect to private channels?

**Comment by FZambia** [comment]
Hi, in all clients other than `centrifuge-js` we call callback function with all data required to build private channel JWT (client ID and channel). See [docs](https://www.javadoc.io/doc/io.github.centrifugal/centrifuge-java/0.0.2) and [example](https://github.com/centrifugal/centrifuge-java/blob/master/example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java#L56). When this callback fired it's up to you to get token from your app backend in a way you want. Then call completion function with string token you got from backend.

**Comment by LuisOzParr** [comment]
Thank you I am checking

**Comment by LuisOzParr** [comment]
We were able to subscribe to a private channel using this method: 
we 
```
private EventListener listener = new EventListener() {

        @Override
        public void onConnect(Client client, ConnectEvent event) {
            super.onConnect(client, event);
            MapsActivity.this.runOnUiThread(() -> Toast.makeText(MapsActivity.this, "onConnect", Toast.LENGTH_SHORT).show());
        }

        @Override
        public void onDisconnect(Client client, DisconnectEvent event) {
            super.onDisconnect(client, event);
            MapsActivity.this.runOnUiThread(() -> Toast.makeText(MapsActivity.this, event.getReason() + " " + event.getReconnect(), Toast.LENGTH_SHORT).show());
        }

        @SuppressLint("SetTextI18n")
        @Override
        public void onMessage(Client client, MessageEvent event) {
            super.onMessage(client, event);
            String data = new String(event.getData());
            MapsActivity.this.runOnUiThread(() -> Toast.makeText(MapsActivity.this, "message from" + sub.getChannel() + " " + data, Toast.LENGTH_SHORT).show());

        }

        @Override
        public void onPrivateSub(Client client, PrivateSubEvent event, TokenCallback cb) {
            
                ProApiInterface apiCall =  ServiceApiClient.getClient().create(ProApiInterface.class);
                Call<ResponseBody> call = apiCall.subScribtePrivate(event.getClient(),event.getChannel());
                call.enqueue(new Callback<ResponseBody>() {
                    @Override
                    public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
                        if (response.body() != null ){
                            String responseBody = null;
                            try {
                                responseBody = response.body().string();
                                MyLog.d(TAG, "Dashboard Response: " + responseBody);
                                JSONObject dashBoardInfo = new JSONObject(responseBody);
                                String token = dashBoardInfo.getString("token");
                                cb.Done(token);
                            } catch (Exception e) {
                                e.printStackTrace();
                                cb.Fail(e);
                            }

                    }

                    @Override
                    public void onFailure(Call<ResponseBody> call, Throwable t) {
                        cb.Fail(t);
                    }
                });
            }

        }
    };
```

**Comment by chishchin** [comment]
> Hi, in all clients other than `centrifuge-js` we call callback function with all data required to build private channel JWT (client ID and channel). See [docs](https://www.javadoc.io/doc/io.github.centrifugal/centrifuge-java/0.0.2) and [example](https://github.com/centrifugal/centrifuge-java/blob/master/example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java#L56). When this callback fired it's up to you to get token from your app backend in a way you want. Then call completion function with string token you got from backend.

Hi, Alexander, can I use callback function in `centrifuge-js` outside of `onPrivateSubscribe`?

**Comment by faizanhaidarkhan** [comment]
> Hi, in all clients other than `centrifuge-js` we call callback function with all data required to build private channel JWT (client ID and channel). See [docs](https://www.javadoc.io/doc/io.github.centrifugal/centrifuge-java/0.0.2) and [example](https://github.com/centrifugal/centrifuge-java/blob/master/example/src/main/java/io/github/centrifugal/centrifuge/example/Main.java#L56). When this callback fired it's up to you to get token from your app backend in a way you want. Then call completion function with string token you got from backend.

But I cant find find Client class in my project, can you plz tell me where is this?

**Comment by stephenchowxingxing** [comment]
> We were able to subscribe to a private channel using this method:
> 
> ```
> private EventListener listener = new EventListener() {
> 
>         @Override
>         public void onConnect(Client client, ConnectEvent event) {
>             super.onConnect(client, event);
>             MapsActivity.this.runOnUiThread(() -> Toast.makeText(MapsActivity.this, "onConnect", Toast.LENGTH_SHORT).show());
>         }
> 
>         @Override
>         public void onDisconnect(Client client, DisconnectEvent event) {
>             super.onDisconnect(client, event);
>             MapsActivity.this.runOnUiThread(() -> Toast.makeText(MapsActivity.this, event.getReason() + " " + event.getReconnect(), Toast.LENGTH_SHORT).show());
>         }
> 
>         @SuppressLint("SetTextI18n")
>         @Override
>         public void onMessage(Client client, MessageEvent event) {
>             super.onMessage(client, event);
>             String data = new String(event.getData());
>             MapsActivity.this.runOnUiThread(() -> Toast.makeText(MapsActivity.this, "message from" + sub.getChannel() + " " + data, Toast.LENGTH_SHORT).show());
> 
>         }
> 
>         @Override
>         public void onPrivateSub(Client client, PrivateSubEvent event, TokenCallback cb) {
>             
>                 ProApiInterface apiCall =  ServiceApiClient.getClient().create(ProApiInterface.class);
>                 Call<ResponseBody> call = apiCall.subScribtePrivate(event.getClient(),event.getChannel());
>                 call.enqueue(new Callback<ResponseBody>() {
>                     @Override
>                     public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
>                         if (response.body() != null ){
>                             String responseBody = null;
>                             try {
>                                 responseBody = response.body().string();
>                                 MyLog.d(TAG, "Dashboard Response: " + responseBody);
>                                 JSONObject dashBoardInfo = new JSONObject(responseBody);
>                                 String token = dashBoardInfo.getString("token");
>                                 cb.Done(token);
>                             } catch (Exception e) {
>                                 e.printStackTrace();
>                                 cb.Fail(e);
>                             }
> 
>                     }
> 
>                     @Override
>                     public void onFailure(Call<ResponseBody> call, Throwable t) {
>                         cb.Fail(t);
>                     }
>                 });
>             }
> 
>         }
>     };
> ```

@LuisOzParr I try to subscribe private channel by this way, but it didn't work. it connected at first, then it disconnect and retry very quickly and never stop. Hope to get your help, thanks!
