### ISSUE TITLE
Bad protocol happens when receiving messages and never reconnect to the server

### ISSUE THREAD

**Issue by tre-hejinyin** [centrifugal/centrifuge-java#49]
Hi there, 
I'm using the "centrifuge-java:0.2.5" in my Android project(backend side: V4.0.1),and endpoint is: wss://xxxx/connection/websocket?format=protobuf&cf_protocol_version=v2.
But when receiving messages, sometimes error happens like this:
1. In EventListener() - onDisconnected() callback: DisconnectedEvent code = 2, reason = "bad protocol"
2. In EventListener() - onError() callback:  ErrorEvent reason = "java.net.SocketException: Socket closed"
After that the SDK never trigger any reconnection and/or onConnected() event as a result we stop receiving new message from the server.

**Comment by FZambia** [comment]
Hello, thanks for report.

If possible please provide a stack trace we are printing when issuing every `bad protocol` disconnect ([example](https://github.com/centrifugal/centrifuge-java/blob/master/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java#L280)).

**Comment by FZambia** [comment]
For those who came across this issue.

One reason why BAD_PROTOCOL [may happen is due to missing](https://github.com/centrifugal/centrifuge-java/blob/90c8464f23d023b6cd096b0bfa7479972bd8b8c1/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java#L357) `TokenGetter` in the SDK configuration. This happens when you are using JWT tokens **with expiration** but have not set `TokenGetter` to config to refresh a token upon expiration. In this case, while not obvious, this is a client configuration issue which can be solved on library user's side – just by properly configuring SDK. Some details about token refresh behaviour may be found [in Centrifugo docs](https://centrifugal.dev/docs/transports/client_api#client-connection-token).

But. BAD_PROTOCOL may also happen due to other exceptions we handle inside the SDK. And reporters of the issue told me that `TokenGetter` is set – so it can't be the issue in this particular case.  At the moment I am not sure from where exactly it may come to address it – that's why stack  trace would be very helpful. I'll try to think more on the possible source though.

**Comment by tre-hejinyin** [comment]
I got the stack trace after I received a message.
![image](https://user-images.githubusercontent.com/38416808/217413441-fd73635e-9268-412d-8341-01d3a10d8152.png)
I guess it comes from here:
![image](https://user-images.githubusercontent.com/38416808/217413553-3512a0c9-7688-470e-9100-c8efea8d839b.png)
Hope this can help you.

**Comment by FZambia** [comment]
@tre-hejinyin thx.

It seems though this exception comes from inside your `onPublication` handler? See `jp.utils..` on top of the stack trace.

Also, we are handling IOException in a custom way in this block. `NullPointerException` is not a subclass of `IOException` – so it can't be a cause BAD_PROTOCOL disconnect.

**Comment by tre-hejinyin** [comment]
We get data from `publicationEvent` like this:
```
subscriptionEventListener = object : SubscriptionEventListener() {
            override fun onPublication(sub: Subscription?, event: PublicationEvent?) {
                val data = String(event!!.data, UTF_8)
                if (data.contains("hybridCartCancelFinish")) {...}
                }
}
```
So the `NullPointerException` exception is mainly caused by the `event.data`
and in function `handlePub` of Client.java, it's 
```
private void handlePub(String channel, Protocol.Publication pub) {
        ClientInfo info = ClientInfo.fromProtocolClientInfo(pub.getInfo());
        Subscription sub = this.getSub(channel);
       ...
```
Is there any chance that this can make it disconnect? This is the only `Exception`I can find in the logs

**Comment by FZambia** [comment]
`info` can be `null` in your case (you should handle this). But as I said – we only handle `IOException` when issuing BAD_PROTOCOL, I don't see how it can result in the  BAD_PROTOCOL disconnect.

**Comment by FZambia** [comment]
> info can be null in your case (you should handle this).

Sorry, I thought the second snippet is from your app. Have not read your comment carefully enough. So you think `data` is null? In general this should not be true as we validate data is set in server API handler. But even if it's null (for example this is possible when publications go from the client side, which is not the way you publish I suppose) - BAD_PROTOCOL should not be the result of NullPointer exception.

**Comment by tre-hejinyin** [comment]
Hmm, you're right. 
FYI, this is what I'm doing in `eventListener` and `subscriptionEventListener`
```
eventListener = object : EventListener() {
            override fun onConnected(client: Client?, event: ConnectedEvent?) {
                writeDebugLog(TAG,"EventListener-onConnected()",String.format("centrifuge connected with client ID %s", event!!.client))
            }

            override fun onDisconnected(client: Client?, event: DisconnectedEvent) {
                writeDebugLog(TAG, "EventListener-onDisconnected()", "centrifuge disconnected,error code: ${event.code}, reason: ${event.reason}")
            }

            override fun onError(client: Client?, event: ErrorEvent?) {
                writeDebugLog(TAG, "EventListener-onError()", "reason: ${event!!.error}")
            }

            override fun onSubscribed(client: Client?, event: ServerSubscribedEvent?) {
                writeDebugLog(TAG, "EventListener-onSubscribed()", "server side subscribed:  ${event!!.channel}, recovered: ${event!!.recovered}")
            }

            override fun onUnsubscribed(client: Client?, event: ServerUnsubscribedEvent?) {
                writeDebugLog(TAG, "EventListener-onUnsubscribed()", "server side unsubscribed:  ${event!!.channel}")
            }

            override fun onJoin(client: Client?, event: ServerJoinEvent?) {
                writeDebugLog(TAG, "EventListener-onJoin()", "server side join:  ${event!!.channel} from client ${event!!.info.client}")
            }

            override fun onLeave(client: Client?, event: ServerLeaveEvent?) {
                writeDebugLog(TAG, "EventListener-onLeave()", "server side leave:  ${event!!.channel} from client ${event!!.info.client}")
            }
        }
```

```
subscriptionEventListener = object : SubscriptionEventListener() {
            override fun onPublication(sub: Subscription?, event: PublicationEvent?) {
                val data = String(event!!.data, UTF_8)
                writeDebugLog(TAG, "onPublish()", "receive data from centrifuge server: $data")

                if (data.contains("hybridPaymentFinish")) {
                    val hybridPaymentNotification =
                        Gson().fromJson(data, HybridPaymentNotification::class.java)
                    if (hybridPaymentNotification.userId == userData.value?.userId
                        && hybridPaymentNotification.deviceUuid == MyApplication.getUUID()
                    ) {
                        isHybridPaymentFinish.postValue(true)
                    }
                }
                println(TAG + "--message from centrifuge channel--" + sub!!.channel + ": " + data)
            }

            override fun onSubscribed(sub: Subscription?, event: SubscribedEvent?) {
                writeDebugLog(TAG, "onSubscribed()", "centrifuge subscribed to ${sub!!.channel}")
            }

            override fun onUnsubscribed(sub: Subscription?, event: UnsubscribedEvent?) {
                writeDebugLog(TAG, "onUnsubscribed()", "reason:  ${event!!.reason}")
            }

            override fun onError(sub: Subscription?, event: SubscriptionErrorEvent?) {
                writeDebugLog(TAG,"SubscriptionEventListener-onError()","subscribe error ${sub!!.channel}: ${event!!.error}")
            }

            override fun onJoin(sub: Subscription?, event: JoinEvent?) {
                writeDebugLog(TAG,"SubscriptionEventListener-onJoin()","client  ${event!!.info.client} joined channel ${sub!!.channel}")
            }

            override fun onLeave(sub: Subscription?, event: LeaveEvent?) {
                writeDebugLog(TAG,"SubscriptionEventListener-onLeave()","client  ${event!!.info.client} left channel ${sub!!.channel}")
            }
        }
```

**Comment by FZambia** [comment]
A bit busy morning, just found more time to look at code – and actually [here](https://github.com/centrifugal/centrifuge-java/blob/90c8464f23d023b6cd096b0bfa7479972bd8b8c1/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java#L291) is a part which will disconnect with BAD_PROTOCOL in case of `NullPointerException` in publication handler. So now the goal is to understand why that `NullPointerException` happens in your handler. Not sure the `data` may be null there.

**Comment by tre-hejinyin** [comment]
Hello, I did some tests this morning, and let's say if this `NullPointerException` happens on my side, the APP will crash, but the reporter said the APP still running. So I personally new a `PublicationEvent` in `onPublication`, the `event.data` is 100% null. Runs that, it goes here: 
![image](https://user-images.githubusercontent.com/38416808/217699847-529b1522-6096-439c-897b-dc44167d0f0c.png)
I'm not sure It's the same issue with my production, will test that soon this afternoon. And will report more details after that.

**Comment by FZambia** [comment]
Latest news here:

* reporters found possible exception inside Publication handler code which could lead to the bad_protocol disconnect and now check the hypothesis
* centrifuge-java [0.2.6](https://github.com/centrifugal/centrifuge-java/releases/tag/0.2.6) contains a couple of improvements which improve errors/exceptions observability to help understand the issue more quickly next time

**Comment by tre-hejinyin** [comment]
Many thanks!
