### ISSUE TITLE
Calling subscribe on subscription causes "already subscribed" error

### ISSUE THREAD

**Issue by PhilipDukhov** [centrifugal/centrifuge-java#51]
I'm using version **1.0.0** of this library, as my server is using Centrifugo v2.

According to [documentation](https://centrifugal.dev/docs/transports/client_api#subscription-states) I should call `subscription.subscribe()` for each subscription.

But when I try doing this, looks like some auto-subscription method is being called, and after some delay(I suspect after auto-subscription succeeds) - when my `subscribe` call starts processing - `SubscriptionEventListener.onSubscribeError` is getting called with `"already subscribed"`.

I could've remove `subscription.subscribe()` but auto-subscription system doesn't seems to be working with private channels - there I still have to call it. And I can't just ignore `onSubscribeError`, because client is closing with `Closing : 1000 / ` log message.

My guess that that I need to call `subscribe` only for private channels - is that correct? Why documentation doesn't mention it?

1. Is there a way to disable auto-subscription system, so I can call `subscription.subscribe()` on each subscription?
2. Is there a way to prevent client from closing on this particular error?

**Comment by FZambia** [comment]
Hello @PhilipDukhov 

You are relying on the modern documentation, but using very old versions of library and server. The [documentation](https://centrifugal.dev/docs/transports/client_api) about client SDK behavior you pointed is only valid for centrifuge-java >= 0.2.2 and Centrifugo v4. For previous versions we did not have such spec.

Sorry, but I can not maintain old versions of library and server – simply no enough resources for this. I suggest upgrading to the latest stack and the everything should work according to the spec in documentation.
