### ISSUE TITLE
How to subscribe to private channel in v2 API?

### ISSUE THREAD

**Issue by PhilipDukhov** [centrifugal/centrifuge-java#52]
I'm using the latest version 0.2.5

I've found [`SubscriptionOptions`](https://github.com/centrifugal/centrifuge-java/blob/cd0c537b452e71f797e5e8d5a68a16aa56ae7c4c/centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionOptions.java#L6) with `token` parameter which looks like what I need, but i don't see a way to pass it - [`newSubscription`](https://github.com/centrifugal/centrifuge-java/blob/cd0c537b452e71f797e5e8d5a68a16aa56ae7c4c/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java#L524) doesn't accept any related parameters and there's no other way to create a subscription.

**Comment by FZambia** [comment]
Let's open till released (hopefully today or tomorrow).

**Comment by FZambia** [comment]
[0.2.6](https://github.com/centrifugal/centrifuge-java/releases/tag/0.2.6) released. Thanks @PhilipDukhov !
