### ISSUE TITLE
pinning

### ISSUE THREAD

**Issue by frakc** [centrifugal/centrifuge-java#6]
Hello, how can we implement certificate pinning if it is possible at all?

**Comment by FZambia** [comment]
Hello, I suppose it's possible with okhttp lib which is used inside this client. See https://stackoverflow.com/questions/24006545/how-can-i-pin-a-certificate-with-square-okhttp

I think the only thing we need to add is possibility to set custom okhttp client to be used for WebSocket connection.

**Comment by frakc** [comment]
got it
